project_id = "tzqxdsxjmpscotdcevdh"

[functions.hello-world]
verify_jwt = false

[functions.remap-curriculum-standards]
verify_jwt = false

[functions.generate-assignment]
verify_jwt = false

[functions.generate-profile-assessment]
verify_jwt = false

[functions.generate-remedial-assignment]
verify_jwt = false

[functions.curriculum-planning-chat]
verify_jwt = false

[functions.generate-study-guide]
verify_jwt = false

[functions.process-curriculum-session]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = true

[functions.detect-standards]
verify_jwt = false

[functions.generate-curriculum]
verify_jwt = false

[functions.generate-course-standards]
verify_jwt = false

[functions.analyze-student-progress]
verify_jwt = true

[functions.analyze-student-mastery]
verify_jwt = false

[functions.generate-weekly-curriculum]
verify_jwt = true

[functions.generate_weekly_curriculum_cron]
verify_jwt = false

[functions.grade-open-response]
verify_jwt = true

[functions.regrade-submission]
verify_jwt = true

[functions.regenerate-pe-course]
verify_jwt = false

[functions.seed-ca-ccss-standards]
verify_jwt = false

[functions.standards-planning-chat]
verify_jwt = false

[functions.research-standards]
verify_jwt = false

[functions.generate-trivia]
verify_jwt = false

