import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Calendar, ArrowLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { MarketingNav } from '@/components/MarketingNav';

export default function PedagogiesSupported() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background">
      <MarketingNav />
      
      <article className="py-24">
        <div className="container mx-auto px-4">
          <div className="max-w-3xl mx-auto space-y-8">
            <Button 
              variant="ghost" 
              className="mb-4"
              onClick={() => navigate('/blog')}
            >
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back to Blog
            </Button>

            <div className="space-y-4">
              <div className="flex items-center gap-2">
                <Badge variant="secondary">Philosophy</Badge>
                <span className="text-sm text-muted-foreground flex items-center gap-1">
                  <Calendar className="h-3 w-3" />
                  January 15, 2025
                </span>
                <span className="text-sm text-muted-foreground">• 10 min read</span>
              </div>
              
              <h1 className="text-4xl md:text-5xl font-bold leading-tight">
                One Platform, Every Pedagogy: How SmartCore Adapts to Your Teaching Philosophy
              </h1>
            </div>

            <div className="prose prose-lg max-w-none space-y-6 text-foreground">
              <p className="text-xl text-muted-foreground">
                From Montessori to Classical, Charlotte Mason to unschooling—discover how our AI-powered platform flexibly supports any educational approach while maintaining academic rigor.
              </p>

              <h2 className="text-2xl font-bold mt-8">The Problem with One-Size-Fits-All Education</h2>
              <p>
                Every family has a different educational philosophy. Some parents swear by Montessori's hands-on discovery. Others follow Charlotte Mason's living books approach. Many blend multiple methodologies based on their child's needs.
              </p>

              <p>
                Traditional curriculum platforms force you into their box. They assume every child learns the same way, at the same pace, with the same materials. But you know your child better than that.
              </p>

              <h2 className="text-2xl font-bold mt-8">How SmartCore Supports Multiple Pedagogies</h2>

              <h3 className="text-xl font-bold mt-6">Classical Education</h3>
              <p>
                Our platform aligns perfectly with the trivium framework. The AI identifies which stage each concept should be taught—grammar, logic, or rhetoric—and generates age-appropriate materials. Memory work gets reinforced through spaced repetition. Socratic discussions can be facilitated through our AI learning coach.
              </p>
              <div className="bg-muted/50 rounded-lg p-6 my-6">
                <p className="font-semibold">Classical families love:</p>
                <ul className="mt-2 space-y-2">
                  <li>Standards-aligned content that maintains rigor</li>
                  <li>Historical timelines automatically integrated</li>
                  <li>Great books discussion prompts generated by AI</li>
                  <li>Latin and Greek root word integration</li>
                </ul>
              </div>

              <h3 className="text-xl font-bold mt-6">Charlotte Mason Method</h3>
              <p>
                Living books, nature study, and narration are core to Charlotte Mason homeschooling. Our platform generates rich literature-based assignments, curates high-quality online resources, and prompts students for oral or written narrations after each lesson.
              </p>
              <div className="bg-muted/50 rounded-lg p-6 my-6">
                <p className="font-semibold">Charlotte Mason families love:</p>
                <ul className="mt-2 space-y-2">
                  <li>Literature-rich curriculum generation</li>
                  <li>Nature study integration with science standards</li>
                  <li>Picture study and composer study prompts</li>
                  <li>Short, focused lessons (20-minute blocks)</li>
                </ul>
              </div>

              <h3 className="text-xl font-bold mt-6">Montessori Philosophy</h3>
              <p>
                Child-led learning with prepared environments. Our diagnostics reveal exactly what each child is ready to learn next, while the curriculum generator creates hands-on activity suggestions that align with state standards. Students choose their learning path; the AI ensures coverage.
              </p>

              <h3 className="text-xl font-bold mt-6">Unit Studies & Thematic Learning</h3>
              <p>
                Want to teach the Renaissance through art, literature, science, and history all at once? Our AI can generate integrated unit studies that weave multiple subjects around a central theme while still hitting required standards.
              </p>

              <h3 className="text-xl font-bold mt-6">Unschooling & Interest-Led Learning</h3>
              <p>
                Follow your child's curiosity while still documenting progress. The platform tracks what standards get covered naturally through their interests and generates gentle prompts for gaps—no forced curriculum, just strategic scaffolding.
              </p>

              <h2 className="text-2xl font-bold mt-8">The Secret: Separating Standards from Methodology</h2>
              <p>
                Here's what makes SmartCore unique: we separate <strong>what</strong> needs to be learned (state standards) from <strong>how</strong> it's learned (your pedagogy).
              </p>

              <p>
                The AI tracks standards mastery in the background. You choose the approach. Want to teach fractions through cooking? The AI generates a recipe-based lesson. Prefer Singapore Math? It adapts. Historical fiction? Living math through nature? The system flexes to your philosophy while ensuring academic accountability.
              </p>

              <h2 className="text-2xl font-bold mt-8">Waldorf, Reggio Emilia, and Progressive Education</h2>
              <p>
                These approaches emphasize creativity, play, and emergent curriculum. Our platform supports this by:
              </p>
              <ul className="space-y-2">
                <li>Allowing fully customizable project-based assignments</li>
                <li>Supporting portfolio-based assessment over testing</li>
                <li>Generating open-ended creative prompts</li>
                <li>Documenting learning that happens outside traditional lessons</li>
              </ul>

              <h2 className="text-2xl font-bold mt-8">Blended & Eclectic Approaches</h2>
              <p>
                Most families don't follow one strict pedagogy. You might use:
              </p>
              <ul className="space-y-2">
                <li>Charlotte Mason for literature and history</li>
                <li>Singapore Math for mathematics</li>
                <li>Classical approach for Latin</li>
                <li>Unit studies for science</li>
              </ul>

              <p>
                Our platform doesn't care. Mix and match. The AI tracks mastery regardless of method.
              </p>

              <h2 className="text-2xl font-bold mt-8">What Parents Tell Us</h2>
              <p>
                "I was terrified switching from boxed curriculum to Charlotte Mason. Would we hit our standards? Turns out, the AI tracks that for me while I focus on beautiful books."
              </p>

              <p>
                "We're classical homeschoolers, and I was skeptical of AI. But it actually <em>strengthens</em> our approach—generating Socratic questions I wouldn't have thought of myself."
              </p>

              <p>
                "As an unschooling family, I needed proof of learning for my state. The platform documents everything my kids learn naturally, mapping it to standards without killing their joy."
              </p>

              <h2 className="text-2xl font-bold mt-8">The Bottom Line</h2>
              <p>
                Your pedagogy shouldn't be dictated by your software. SmartCore is the first platform that truly adapts to <em>your</em> teaching philosophy while maintaining the academic accountability required by states, colleges, and testing agencies.
              </p>

              <p>
                Whether you're a die-hard Montessorian or an eclectic blender, whether you worship Charlotte Mason or follow your child's lead—the platform works for you, not against you.
              </p>

              <p className="text-xl font-semibold">
                One platform. Every pedagogy. Finally.
              </p>

              <div className="border-t pt-8 mt-12">
                <p className="text-muted-foreground italic">
                  Ready to homeschool your way—with AI support?
                </p>
                <Button 
                  size="lg" 
                  className="mt-4"
                  onClick={() => navigate('/auth')}
                >
                  Start Free Trial
                </Button>
              </div>
            </div>
          </div>
        </div>
      </article>
    </div>
  );
}
