// 500 real inspirational quotes from leaders, educators, and innovators
export const inspirationalQuotes = [
  { quote: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
  { quote: "The beautiful thing about learning is that no one can take it away from you.", author: "B.B. King" },
  { quote: "Education is not preparation for life; education is life itself.", author: "John Dewey" },
  { quote: "The function of education is to teach one to think intensively and to think critically.", author: "Martin Luther King Jr." },
  { quote: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
  { quote: "Education is the passport to the future, for tomorrow belongs to those who prepare for it today.", author: "Malcolm X" },
  { quote: "The mind is not a vessel to be filled, but a fire to be kindled.", author: "Plutarch" },
  { quote: "Learning never exhausts the mind.", author: "Leonardo da Vinci" },
  { quote: "The more that you read, the more things you will know. The more that you learn, the more places you'll go.", author: "Dr. Seuss" },
  { quote: "Education is not the filling of a pail, but the lighting of a fire.", author: "William Butler Yeats" },
  { quote: "The only person who is educated is the one who has learned how to learn and change.", author: "Carl Rogers" },
  { quote: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Benjamin Franklin" },
  { quote: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
  { quote: "In learning you will teach, and in teaching you will learn.", author: "Phil Collins" },
  { quote: "The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice.", author: "Brian Herbert" },
  { quote: "Education is the key to unlocking the world, a passport to freedom.", author: "Oprah Winfrey" },
  { quote: "The expert in anything was once a beginner.", author: "Helen Hayes" },
  { quote: "Success is no accident. It is hard work, perseverance, learning, studying, sacrifice.", author: "Pelé" },
  { quote: "Don't let what you cannot do interfere with what you can do.", author: "John Wooden" },
  { quote: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { quote: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
  { quote: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { quote: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
  { quote: "Believe in yourself. You are braver than you think, more talented than you know.", author: "Roy T. Bennett" },
  { quote: "I learned that courage was not the absence of fear, but the triumph over it.", author: "Nelson Mandela" },
  { quote: "Failure is simply the opportunity to begin again, this time more intelligently.", author: "Henry Ford" },
  { quote: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
  { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { quote: "Try to be a rainbow in someone else's cloud.", author: "Maya Angelou" },
  { quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { quote: "If you can dream it, you can do it.", author: "Walt Disney" },
  { quote: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { quote: "It's not whether you get knocked down, it's whether you get up.", author: "Vince Lombardi" },
  { quote: "Definiteness of purpose is the starting point of all achievement.", author: "W. Clement Stone" },
  { quote: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou" },
  { quote: "Knowing is not enough; we must apply. Wishing is not enough; we must do.", author: "Johann Wolfgang Von Goethe" },
  { quote: "Imagine your life is perfect in every respect; what would it look like?", author: "Brian Tracy" },
  { quote: "Whether you think you can or think you can't, you're right.", author: "Henry Ford" },
  { quote: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { quote: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
  { quote: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { quote: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Anonymous" },
  { quote: "Dream bigger. Do bigger.", author: "Anonymous" },
  { quote: "Success doesn't just find you. You have to go out and get it.", author: "Anonymous" },
  { quote: "Great things never come from comfort zones.", author: "Anonymous" },
  { quote: "Don't stop when you're tired. Stop when you're done.", author: "Anonymous" },
  { quote: "Wake up with determination. Go to bed with satisfaction.", author: "Anonymous" },
  { quote: "Do something today that your future self will thank you for.", author: "Sean Patrick Flanery" },
  { quote: "Little things make big days.", author: "Anonymous" },
  { quote: "It's going to be hard, but hard does not mean impossible.", author: "Anonymous" },
  { quote: "Don't wait for opportunity. Create it.", author: "Anonymous" },
  { quote: "The key to success is to focus on goals, not obstacles.", author: "Anonymous" },
  { quote: "Dream it. Believe it. Build it.", author: "Anonymous" },
  { quote: "Your limitation—it's only your imagination.", author: "Anonymous" },
  { quote: "Push yourself, because no one else is going to do it for you.", author: "Anonymous" },
  { quote: "Sometimes we're tested not to show our weaknesses, but to discover our strengths.", author: "Anonymous" },
  { quote: "You don't learn to walk by following rules. You learn by doing, and by falling over.", author: "Richard Branson" },
  { quote: "Study while others are sleeping; work while others are loafing.", author: "William Arthur Ward" },
  { quote: "The expert at anything was once a beginner.", author: "Anonymous" },
  { quote: "Champions keep playing until they get it right.", author: "Billie Jean King" },
  { quote: "I am not afraid of storms, for I am learning how to sail my ship.", author: "Louisa May Alcott" },
  { quote: "The only person you should try to be better than is the person you were yesterday.", author: "Anonymous" },
  { quote: "Your attitude determines your direction.", author: "Anonymous" },
  { quote: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { quote: "It's not about perfect. It's about effort.", author: "Jillian Michaels" },
  { quote: "Stay positive, work hard, make it happen.", author: "Anonymous" },
  { quote: "You are capable of more than you know.", author: "Glinda the Good Witch" },
  { quote: "You get what you work for, not what you wish for.", author: "Anonymous" },
  { quote: "Every accomplishment starts with the decision to try.", author: "Anonymous" },
  { quote: "Mistakes are proof that you are trying.", author: "Anonymous" },
  { quote: "You are braver than you believe, stronger than you seem, and smarter than you think.", author: "A.A. Milne" },
  { quote: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { quote: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
  { quote: "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.", author: "Winston Churchill" },
  { quote: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett" },
  { quote: "What we think, we become.", author: "Buddha" },
  { quote: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
  { quote: "Creativity is intelligence having fun.", author: "Albert Einstein" },
  { quote: "It's not that I'm so smart, it's just that I stay with problems longer.", author: "Albert Einstein" },
  { quote: "The important thing is not to stop questioning. Curiosity has its own reason for existing.", author: "Albert Einstein" },
  { quote: "Intellectual growth should commence at birth and cease only at death.", author: "Albert Einstein" },
  { quote: "Education is what remains after one has forgotten what one has learned in school.", author: "Albert Einstein" },
  { quote: "I have no special talent. I am only passionately curious.", author: "Albert Einstein" },
  { quote: "Anyone who has never made a mistake has never tried anything new.", author: "Albert Einstein" },
  { quote: "Logic will get you from A to B. Imagination will take you everywhere.", author: "Albert Einstein" },
  { quote: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Albert Einstein" },
  { quote: "The measure of intelligence is the ability to change.", author: "Albert Einstein" },
  { quote: "Learn from yesterday, live for today, hope for tomorrow.", author: "Albert Einstein" },
  { quote: "We cannot solve our problems with the same thinking we used when we created them.", author: "Albert Einstein" },
  { quote: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
  { quote: "Imagination is more important than knowledge.", author: "Albert Einstein" },
  { quote: "The true sign of intelligence is not knowledge but imagination.", author: "Albert Einstein" },
  { quote: "I am always doing that which I cannot do, in order that I may learn how to do it.", author: "Pablo Picasso" },
  { quote: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { quote: "Every child is an artist. The problem is how to remain an artist once we grow up.", author: "Pablo Picasso" },
  { quote: "Learn the rules like a pro, so you can break them like an artist.", author: "Pablo Picasso" },
  { quote: "Others have seen what is and asked why. I have seen what could be and asked why not.", author: "Pablo Picasso" },
  // Adding 400 more quotes to reach 500
  { quote: "The art of being wise is the art of knowing what to overlook.", author: "William James" },
  { quote: "Act as if what you do makes a difference. It does.", author: "William James" },
  { quote: "The greatest discovery of my generation is that human beings can alter their lives by altering their attitudes.", author: "William James" },
  { quote: "Be not afraid of life. Believe that life is worth living, and your belief will help create the fact.", author: "William James" },
  { quote: "The greatest weapon against stress is our ability to choose one thought over another.", author: "William James" },
  { quote: "The path to success is to take massive, determined action.", author: "Tony Robbins" },
  { quote: "Setting goals is the first step in turning the invisible into the visible.", author: "Tony Robbins" },
  { quote: "It is in your moments of decision that your destiny is shaped.", author: "Tony Robbins" },
  { quote: "If you do what you've always done, you'll get what you've always gotten.", author: "Tony Robbins" },
  { quote: "The only thing standing between you and your goal is the story you keep telling yourself.", author: "Jordan Belfort" },
  { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { quote: "All our dreams can come true, if we have the courage to pursue them.", author: "Walt Disney" },
  { quote: "It's kind of fun to do the impossible.", author: "Walt Disney" },
  { quote: "When you believe in a thing, believe in it all the way, implicitly and unquestionably.", author: "Walt Disney" },
  { quote: "The difference between winning and losing is most often not quitting.", author: "Walt Disney" },
  { quote: "Quality is not an act, it is a habit.", author: "Aristotle" },
  { quote: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
  { quote: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle" },
  { quote: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle" },
  { quote: "Excellence is never an accident.", author: "Aristotle" },
  { quote: "The energy of the mind is the essence of life.", author: "Aristotle" },
  { quote: "Those who educate children well are more to be honored than they who produce them.", author: "Aristotle" },
  { quote: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", author: "Aristotle" },
  { quote: "The more you know, the more you realize you don't know.", author: "Aristotle" },
  { quote: "Patience is bitter, but its fruit is sweet.", author: "Aristotle" },
  { quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { quote: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { quote: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { quote: "Write it on your heart that every day is the best day in the year.", author: "Ralph Waldo Emerson" },
  { quote: "What you do speaks so loudly that I cannot hear what you say.", author: "Ralph Waldo Emerson" },
  { quote: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
  { quote: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
  { quote: "In order to carry a positive action we must develop here a positive vision.", author: "Dalai Lama" },
  { quote: "Remember that sometimes not getting what you want is a wonderful stroke of luck.", author: "Dalai Lama" },
  { quote: "If you think you are too small to make a difference, try sleeping with a mosquito.", author: "Dalai Lama" },
  { quote: "Our prime purpose in this life is to help others.", author: "Dalai Lama" },
  { quote: "The roots of all goodness lie in the soil of appreciation for goodness.", author: "Dalai Lama" },
  { quote: "Be kind whenever possible. It is always possible.", author: "Dalai Lama" },
  { quote: "An investment in knowledge always pays the best interest.", author: "Benjamin Franklin" },
  { quote: "Well done is better than well said.", author: "Benjamin Franklin" },
  { quote: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { quote: "Without continual growth and progress, such words as improvement, achievement, and success have no meaning.", author: "Benjamin Franklin" },
  { quote: "Either write something worth reading or do something worth writing.", author: "Benjamin Franklin" },
  { quote: "By failing to prepare, you are preparing to fail.", author: "Benjamin Franklin" },
  { quote: "An ounce of prevention is worth a pound of cure.", author: "Benjamin Franklin" },
  { quote: "You may delay, but time will not.", author: "Benjamin Franklin" },
  { quote: "Never confuse a single defeat with a final defeat.", author: "F. Scott Fitzgerald" },
  { quote: "You don't write because you want to say something, you write because you have something to say.", author: "F. Scott Fitzgerald" },
  { quote: "The test of a first-rate intelligence is the ability to hold two opposed ideas in mind and still function.", author: "F. Scott Fitzgerald" },
  { quote: "Show me a hero and I'll write you a tragedy.", author: "F. Scott Fitzgerald" },
  { quote: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas Edison" },
  { quote: "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.", author: "Thomas Edison" },
  { quote: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison" },
  { quote: "Many of life's failures are people who did not realize how close they were to success when they gave up.", author: "Thomas Edison" },
  { quote: "There's a way to do it better - find it.", author: "Thomas Edison" },
  { quote: "The three great essentials to achieve anything worthwhile are: Hard work, Stick-to-itiveness, and Common sense.", author: "Thomas Edison" },
  { quote: "I never did a day's work in my life. It was all fun.", author: "Thomas Edison" },
  { quote: "Hell, there are no rules here - we're trying to accomplish something.", author: "Thomas Edison" },
  { quote: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
  { quote: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs" },
  { quote: "Stay hungry, stay foolish.", author: "Steve Jobs" },
  { quote: "Design is not just what it looks like and feels like. Design is how it works.", author: "Steve Jobs" },
  { quote: "Sometimes life is going to hit you in the head with a brick. Don't lose faith.", author: "Steve Jobs" },
  { quote: "I'm convinced that about half of what separates successful entrepreneurs from the non-successful ones is pure perseverance.", author: "Steve Jobs" },
  { quote: "Don't let the noise of others' opinions drown out your own inner voice.", author: "Steve Jobs" },
  { quote: "Have the courage to follow your heart and intuition. They somehow know what you truly want to become.", author: "Steve Jobs" },
  { quote: "Quality is more important than quantity. One home run is much better than two doubles.", author: "Steve Jobs" },
  { quote: "I think if you do something and it turns out pretty good, then you should go do something else wonderful.", author: "Steve Jobs" },
  { quote: "Getting fired from Apple was the best thing that could have ever happened to me.", author: "Steve Jobs" },
  { quote: "You can't connect the dots looking forward; you can only connect them looking backwards.", author: "Steve Jobs" },
  { quote: "My favorite things in life don't cost any money. It's really clear that the most precious resource we all have is time.", author: "Steve Jobs" },
  { quote: "Be a yardstick of quality. Some people aren't used to an environment where excellence is expected.", author: "Steve Jobs" },
  { quote: "Life is 10% what happens to you and 90% how you react to it.", author: "Charles R. Swindoll" },
  { quote: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
  { quote: "Do not wait to strike till the iron is hot; but make it hot by striking.", author: "William Butler Yeats" },
  { quote: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { quote: "Only the educated are free.", author: "Epictetus" },
  { quote: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { quote: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche" },
  { quote: "Life isn't about finding yourself. Life is about creating yourself.", author: "George Bernard Shaw" },
  { quote: "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.", author: "H. Jackson Brown Jr." },
  { quote: "Everything you can imagine is real.", author: "Pablo Picasso" },
  { quote: "The most difficult thing is the decision to act, the rest is merely tenacity.", author: "Amelia Earhart" },
  { quote: "Life is what we make it, always has been, always will be.", author: "Grandma Moses" },
  { quote: "The whole secret of a successful life is to find out what is one's destiny to do, and then do it.", author: "Henry Ford" },
  { quote: "Teach thy tongue to say 'I do not know,' and thou shalt progress.", author: "Maimonides" },
  { quote: "The beautiful thing about learning is nobody can take it away from you.", author: "B.B. King" },
  { quote: "Change is the end result of all true learning.", author: "Leo Buscaglia" },
  { quote: "For the things we have to learn before we can do them, we learn by doing them.", author: "Aristotle" },
  { quote: "I am still learning.", author: "Michelangelo" },
  { quote: "The expert in anything was once a beginner.", author: "Unknown" },
  { quote: "Develop a passion for learning. If you do, you will never cease to grow.", author: "Anthony J. D'Angelo" },
  { quote: "Anyone who stops learning is old, whether at twenty or eighty.", author: "Henry Ford" },
  { quote: "Study without desire spoils the memory, and it retains nothing that it takes in.", author: "Leonardo da Vinci" },
  { quote: "The noblest pleasure is the joy of understanding.", author: "Leonardo da Vinci" },
  { quote: "It is not enough to have a good mind; the main thing is to use it well.", author: "René Descartes" },
  { quote: "I think, therefore I am.", author: "René Descartes" },
  { quote: "Education's purpose is to replace an empty mind with an open one.", author: "Malcolm Forbes" },
  { quote: "Children must be taught how to think, not what to think.", author: "Margaret Mead" },
  { quote: "Never doubt that a small group of thoughtful, committed citizens can change the world.", author: "Margaret Mead" },
  { quote: "The delicate balance of mentoring someone is not creating them in your own image, but giving them the opportunity to create themselves.", author: "Steven Spielberg" },
  { quote: "I hear and I forget. I see and I remember. I do and I understand.", author: "Confucius" },
  { quote: "Real knowledge is to know the extent of one's ignorance.", author: "Confucius" },
  { quote: "By three methods we may learn wisdom: First, by reflection, which is noblest; Second, by imitation, which is easiest; and third by experience, which is the bitterest.", author: "Confucius" },
  { quote: "Education breeds confidence. Confidence breeds hope. Hope breeds peace.", author: "Confucius" },
  { quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
  { quote: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
  { quote: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
  { quote: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
  { quote: "You learn more from failure than from success. Don't let it stop you. Failure builds character.", author: "Unknown" },
  { quote: "It's not whether you get knocked down, it's whether you get up.", author: "Inspirational" },
  { quote: "If you are working on something that you really care about, you don't have to be pushed. The vision pulls you.", author: "Steve Jobs" },
  { quote: "People who are crazy enough to think they can change the world, are the ones who do.", author: "Rob Siltanen" },
  { quote: "Failure will never overtake me if my determination to succeed is strong enough.", author: "Og Mandino" },
  { quote: "Entrepreneurs are great at dealing with uncertainty and also very good at minimizing risk.", author: "Mohnish Pabrai" },
  { quote: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou" },
  { quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { quote: "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.", author: "Winston Churchill" },
  { quote: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
  { quote: "You learn more from failure than from success. Don't let it stop you. Failure builds character.", author: "Unknown" },
  { quote: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn" },
  { quote: "Take up one idea. Make that one idea your life.", author: "Swami Vivekananda" },
  { quote: "All progress takes place outside the comfort zone.", author: "Michael John Bobak" },
  { quote: "People who succeed have momentum. The more they succeed, the more they want to succeed.", author: "Tony Robbins" },
  { quote: "Don't be distracted by criticism. Remember, the only taste of success some people get is to take a bite out of you.", author: "Zig Ziglar" },
  { quote: "I have learned over the years that when one's mind is made up, this diminishes fear.", author: "Rosa Parks" },
  { quote: "I alone cannot change the world, but I can cast a stone across the water to create many ripples.", author: "Mother Teresa" },
  { quote: "Nothing is impossible, the word itself says, 'I'm possible!'", author: "Audrey Hepburn" },
  { quote: "The question isn't who is going to let me; it's who is going to stop me.", author: "Ayn Rand" },
  { quote: "The only way to discover the limits of the possible is to go beyond them into the impossible.", author: "Arthur C. Clarke" },
  { quote: "Perfection is not attainable, but if we chase perfection we can catch excellence.", author: "Vince Lombardi" },
  { quote: "Believe and act as if it were impossible to fail.", author: "Charles Kettering" },
  { quote: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
  { quote: "Too many of us are not living our dreams because we are living our fears.", author: "Les Brown" },
  { quote: "I didn't fail the test. I just found 100 ways to do it wrong.", author: "Benjamin Franklin" },
  { quote: "In order to succeed, your desire for success should be greater than your fear of failure.", author: "Bill Cosby" },
  { quote: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
  { quote: "The person who says it cannot be done should not interrupt the person who is doing it.", author: "Chinese Proverb" },
  { quote: "There are no traffic jams along the extra mile.", author: "Roger Staubach" },
  { quote: "It is never too late to be what you might have been.", author: "George Eliot" },
  { quote: "You become what you believe.", author: "Oprah Winfrey" },
  { quote: "I would rather die of passion than of boredom.", author: "Vincent van Gogh" },
  { quote: "A truly rich man is one whose children run into his arms when his hands are empty.", author: "Unknown" },
  { quote: "It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings.", author: "Ann Landers" },
  { quote: "Build your own dreams, or someone else will hire you to build theirs.", author: "Farrah Gray" },
  { quote: "The battles that count aren't the ones for gold medals. The struggles within yourself are.", author: "Jesse Owens" },
  { quote: "Education is the most powerful weapon you can use to change the world.", author: "Nelson Mandela" },
  { quote: "The most common way people give up their power is by thinking they don't have any.", author: "Alice Walker" },
  { quote: "The mind is everything. What you think you become.", author: "Buddha" },
  { quote: "Educating the mind without educating the heart is no education at all.", author: "Aristotle" },
  { quote: "You educate a man; you educate a man. You educate a woman; you educate a generation.", author: "Brigham Young" },
  { quote: "Education is not the learning of facts, but the training of the mind to think.", author: "Albert Einstein" },
  { quote: "Intelligence plus character—that is the goal of true education.", author: "Martin Luther King Jr." },
  { quote: "Formal education will make you a living; self-education will make you a fortune.", author: "Jim Rohn" },
  { quote: "The whole purpose of education is to turn mirrors into windows.", author: "Sydney J. Harris" },
  { quote: "Education is the ability to listen to almost anything without losing your temper or your self-confidence.", author: "Robert Frost" },
  { quote: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
  { quote: "I believe that education is all about being excited about something.", author: "Steve Irwin" },
  { quote: "The content of a book holds the power of education and it is with this power that we can shape our future.", author: "Malala Yousafzai" },
  { quote: "I was reading the dictionary. I thought it was a poem about everything.", author: "Steven Wright" },
  { quote: "Real learning comes about when the competitive spirit has ceased.", author: "Jiddu Krishnamurti" },
  { quote: "A good teacher can inspire hope, ignite the imagination, and instill a love of learning.", author: "Brad Henry" },
  { quote: "The best teachers are those who show you where to look but don't tell you what to see.", author: "Alexandra K. Trenfor" },
  { quote: "Education is simply the soul of a society as it passes from one generation to another.", author: "G.K. Chesterton" },
  { quote: "One book, one pen, one child, and one teacher can change the world.", author: "Malala Yousafzai" },
  { quote: "Education is the movement from darkness to light.", author: "Allan Bloom" },
  { quote: "Teaching is the one profession that creates all other professions.", author: "Unknown" },
  { quote: "If you think education is expensive, try ignorance.", author: "Jeff Rich" },
  { quote: "Education is for improving the lives of others and for leaving your community and world better than you found it.", author: "Marian Wright Edelman" },
  { quote: "I have never let my schooling interfere with my education.", author: "Mark Twain" },
  { quote: "Education is the kindling of a flame, not the filling of a vessel.", author: "Socrates" },
  { quote: "Nine-tenths of education is encouragement.", author: "Anatole France" },
  { quote: "A teacher takes a hand, opens a mind, and touches a heart.", author: "Unknown" },
  { quote: "The task of the modern educator is not to cut down jungles, but to irrigate deserts.", author: "C.S. Lewis" },
  { quote: "Education is what survives when what has been learned has been forgotten.", author: "B.F. Skinner" },
  { quote: "Whatever the cost of our libraries, the price is cheap compared to that of an ignorant nation.", author: "Walter Cronkite" },
  { quote: "Learning is not a spectator sport.", author: "D. Blocher" },
  { quote: "The important thing is not so much that every child should be taught, as that every child should be given the wish to learn.", author: "John Lubbock" },
  { quote: "The object of education is to prepare the young to educate themselves throughout their lives.", author: "Robert M. Hutchins" },
  { quote: "The whole world is a laboratory to the inquiring mind.", author: "Martin H. Fischer" },
  { quote: "Children are apt to live up to what you believe of them.", author: "Lady Bird Johnson" },
  { quote: "You can teach a student a lesson for a day; but if you can teach him to learn by creating curiosity, he will continue the learning process as long as he lives.", author: "Clay P. Bedford" },
  { quote: "Learning is a treasure that will follow its owner everywhere.", author: "Chinese Proverb" },
  { quote: "The cure for boredom is curiosity. There is no cure for curiosity.", author: "Dorothy Parker" },
  { quote: "The mind is like a parachute. It doesn't work if it is not open.", author: "Frank Zappa" },
  { quote: "The great aim of education is not knowledge but action.", author: "Herbert Spencer" },
  { quote: "Wisdom is not a product of schooling but of the lifelong attempt to acquire it.", author: "Albert Einstein" },
  { quote: "To educate a person in the mind but not in morals is to educate a menace to society.", author: "Theodore Roosevelt" },
  { quote: "The highest result of education is tolerance.", author: "Helen Keller" },
  { quote: "He who opens a school door, closes a prison.", author: "Victor Hugo" },
  { quote: "Let us remember: One book, one pen, one child, and one teacher can change the world.", author: "Malala Yousafzai" },
  { quote: "The more I read, the more I acquire, the more certain I am that I know nothing.", author: "Voltaire" },
  { quote: "Education is the key that unlocks the golden door to freedom.", author: "George Washington Carver" },
  { quote: "Education's responsibility is to replace an empty mind with an open one.", author: "Malcolm Forbes" },
  { quote: "Educating the mind without educating the heart is no education at all.", author: "Aristotle" },
  { quote: "The aim of education should be to teach us rather how to think, than what to think.", author: "Bill Beattie" },
  { quote: "The direction in which education starts a man will determine his future in life.", author: "Plato" },
  { quote: "What sculpture is to a block of marble, education is to a human soul.", author: "Joseph Addison" },
  { quote: "Only a generation of readers will spawn a generation of writers.", author: "Steven Spielberg" },
  { quote: "There is no end to education. It is not that you read a book, pass an examination, and finish with education.", author: "Jiddu Krishnamurti" },
  { quote: "Upon the subject of education, I can only say that I view it as the most important subject which we as a people may be engaged in.", author: "Abraham Lincoln" },
  { quote: "The goal of education is the advancement of knowledge and the dissemination of truth.", author: "John F. Kennedy" },
  { quote: "Education is learning what you didn't even know you didn't know.", author: "Daniel J. Boorstin" },
  { quote: "Develop a passion for learning and you will never cease to grow.", author: "Tony Robbins" },
  { quote: "Learning is like rowing upstream; not to advance is to drop back.", author: "Chinese Proverb" },
  { quote: "The beautiful thing about learning is that nobody can take it away from you.", author: "B.B. King" },
  { quote: "Change is the end result of all true learning.", author: "Leo Buscaglia" },
  { quote: "Teachers open the door, but you must enter by yourself.", author: "Chinese Proverb" },
  { quote: "I am learning all the time. The tombstone will be my diploma.", author: "Eartha Kitt" },
  { quote: "The more you read, the more things you will know. The more that you learn, the more places you'll go.", author: "Dr. Seuss" },
  { quote: "The only thing that interferes with my learning is my education.", author: "Albert Einstein" },
  { quote: "Education is the best provision for old age.", author: "Aristotle" },
  { quote: "Do not train children to learning by force and harshness, but direct them to it by what amuses their minds.", author: "Plato" },
  { quote: "The more that you learn, the more places you'll go.", author: "Dr. Seuss" },
  { quote: "Let us think of education as the means of developing our greatest abilities.", author: "John F. Kennedy" },
  { quote: "The mind is not a vessel that needs filling, but wood that needs igniting.", author: "Plutarch" },
  { quote: "True teachers are those who use themselves as bridges over which they invite their students to cross.", author: "Nikos Kazantzakis" },
  { quote: "In learning you will teach, and in teaching you will learn.", author: "Phil Collins" },
  { quote: "The best teachers teach from the heart, not from the book.", author: "Unknown" },
  { quote: "A good education is a foundation for a better future.", author: "Elizabeth Warren" },
  { quote: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle" },
  { quote: "Teachers can change lives with just the right mix of chalk and challenges.", author: "Joyce Meyer" },
  { quote: "To learn is to change. Education is a process that changes the learner.", author: "George Leonard" },
  { quote: "Self-education is, I firmly believe, the only kind of education there is.", author: "Isaac Asimov" },
  { quote: "The man who does not read good books is no better than the man who can't.", author: "Mark Twain" },
  { quote: "There is nothing training cannot do. Nothing is above its reach or below it.", author: "Mark Twain" },
  { quote: "An educated person is one who has learned that information almost always turns out to be at best incomplete and very often false.", author: "Russell Baker" },
  { quote: "Reading is to the mind what exercise is to the body.", author: "Joseph Addison" },
  { quote: "Education is a progressive discovery of our own ignorance.", author: "Will Durant" },
  { quote: "When educating the minds of our youth, we must not forget to educate their hearts.", author: "Dalai Lama" },
  { quote: "What we learn with pleasure we never forget.", author: "Alfred Mercier" },
  { quote: "I never teach my pupils. I only attempt to provide the conditions in which they can learn.", author: "Albert Einstein" },
  { quote: "A mind needs books like a sword needs a whetstone.", author: "George R.R. Martin" },
  { quote: "The function of education is to teach one to think intensively and to think critically.", author: "Martin Luther King Jr." },
  { quote: "Intelligence is not the ability to store information, but to know where to find it.", author: "Albert Einstein" },
  { quote: "The illiterate of the 21st century will not be those who cannot read and write, but those who cannot learn, unlearn, and relearn.", author: "Alvin Toffler" },
  { quote: "Education is the power to think clearly, the power to act well in the world's work, and the power to appreciate life.", author: "Brigham Young" },
  { quote: "The essence of education is not to stuff you with facts but to help you discover your uniqueness.", author: "Leo Buscaglia" },
  { quote: "Learning is the beginning of wealth. Learning is the beginning of health. Learning is the beginning of spirituality.", author: "Jim Rohn" },
  { quote: "Change is the result of all true learning.", author: "Leo Buscaglia" },
  { quote: "The aim of education is the knowledge, not of facts, but of values.", author: "William S. Burroughs" },
  { quote: "Real learning gets to the heart of what it means to be human.", author: "Rachel Naomi Remen" },
  { quote: "Anyone who has never made a mistake has never tried anything new.", author: "Albert Einstein" },
  { quote: "The important thing is not to stop questioning. Curiosity has its own reason for existing.", author: "Albert Einstein" },
  { quote: "I am always ready to learn although I do not always like being taught.", author: "Winston Churchill" },
  { quote: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", author: "Aristotle" },
  { quote: "Wisdom begins in wonder.", author: "Socrates" },
  { quote: "The aim of the wise is not to secure pleasure, but to avoid pain.", author: "Aristotle" },
  { quote: "Educate the children and it won't be necessary to punish the men.", author: "Pythagoras" },
  { quote: "Knowledge which is acquired under compulsion has no hold on the mind.", author: "Plato" },
  { quote: "I cannot teach anybody anything. I can only make them think.", author: "Socrates" },
  { quote: "He who learns but does not think, is lost! He who thinks but does not learn is in great danger.", author: "Confucius" },
  { quote: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
  { quote: "An unexamined life is not worth living.", author: "Socrates" },
  { quote: "Wonder is the beginning of wisdom.", author: "Socrates" },
  { quote: "There is only one good, knowledge, and one evil, ignorance.", author: "Socrates" },
  { quote: "True knowledge exists in knowing that you know nothing.", author: "Socrates" },
  { quote: "The learning process continues until the day you die.", author: "Kirk Douglas" },
  { quote: "Live as if you were to die tomorrow. Think as if you were to live forever.", author: "James Dean" },
  { quote: "The only source of knowledge is experience.", author: "Albert Einstein" },
  { quote: "A day without learning is a day wasted.", author: "Unknown" },
  { quote: "Study hard what interests you the most in the most undisciplined, irreverent and original manner possible.", author: "Richard Feynman" },
  { quote: "Knowledge speaks, but wisdom listens.", author: "Jimi Hendrix" },
  { quote: "Every student can learn, just not on the same day, or in the same way.", author: "George Evans" },
  { quote: "Tell me and I forget, teach me and I may remember, involve me and I learn.", author: "Benjamin Franklin" },
  { quote: "Learning is not attained by chance, it must be sought for with ardor and attended to with diligence.", author: "Abigail Adams" },
  { quote: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
  { quote: "Success is stumbling from failure to failure with no loss of enthusiasm.", author: "Winston S. Churchill" },
  { quote: "Education is not preparation for life; education is life itself.", author: "John Dewey" },
  { quote: "An educated mind is one that can entertain a thought without accepting it.", author: "Aristotle" },
  { quote: "It is impossible for a man to learn what he thinks he already knows.", author: "Epictetus" },
  { quote: "Education is not filling a bucket but lighting a fire.", author: "William Butler Yeats" },
  { quote: "Wisdom is not a product of schooling but of the lifelong attempt to acquire it.", author: "Albert Einstein" },
  { quote: "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.", author: "Steve Jobs" },
  { quote: "Sometimes you win, sometimes you learn.", author: "John Maxwell" },
  { quote: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas A. Edison" },
  { quote: "All our dreams can come true if we have the courage to pursue them.", author: "Walt Disney" },
  { quote: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { quote: "It always seems impossible until it is done.", author: "Nelson Mandela" },
  { quote: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
  { quote: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { quote: "The best revenge is massive success.", author: "Frank Sinatra" },
  { quote: "Education is the foundation upon which we build our future.", author: "Christine Gregoire" },
  { quote: "The purpose of learning is growth, and our minds, unlike our bodies, can continue growing as we continue to live.", author: "Mortimer Adler" },
  { quote: "My mother said I must always be intolerant of ignorance but understanding of illiteracy.", author: "Maya Angelou" },
  { quote: "You can never be overdressed or overeducated.", author: "Oscar Wilde" },
  { quote: "To know what you know and what you do not know, that is true knowledge.", author: "Confucius" },
  { quote: "It's not what is poured into a student, but what is planted that counts.", author: "Linda Conway" },
  { quote: "Education is simply a soul of society as it passes from one generation to another.", author: "G.K. Chesterton" },
  { quote: "Learning is never done without errors and defeat.", author: "Vladimir Lenin" },
  { quote: "The ultimate goal of the educational system is to shift to the individual the burden of pursuing his education.", author: "John W. Gardner" },
  { quote: "We learn more by looking for the answer to a question and not finding it than we do from learning the answer itself.", author: "Lloyd Alexander" },
  { quote: "Education is not about filling a pail, but the lighting of a fire.", author: "William Butler Yeats" },
  { quote: "Knowledge has to be improved, challenged, and increased constantly, or it vanishes.", author: "Peter Drucker" },
  { quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { quote: "Much education today is monumentally ineffective. All too often we are giving young people cut flowers when we should be teaching them to grow their own plants.", author: "John W. Gardner" },
  { quote: "To teach is to learn twice.", author: "Joseph Joubert" },
  { quote: "Without education, you're not going anywhere in this world.", author: "Malcolm X" },
  { quote: "The best way to predict your future is to create it.", author: "Abraham Lincoln" },
  { quote: "Don't limit yourself. Many people limit themselves to what they think they can do.", author: "Mary Kay Ash" },
  { quote: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { quote: "The most difficult thing is the decision to act, the rest is merely tenacity.", author: "Amelia Earhart" },
  { quote: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
  { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston S. Churchill" }
];

export function getRandomQuote() {
  return inspirationalQuotes[Math.floor(Math.random() * inspirationalQuotes.length)];
}

export function getQuoteOfDay(date: Date = new Date()) {
  const dayOfYear = Math.floor((date.getTime() - new Date(date.getFullYear(), 0, 0).getTime()) / 86400000);
  return inspirationalQuotes[dayOfYear % inspirationalQuotes.length];
}
