-- Seed CA-CCSS English/Language Arts Standards for Grade 9-10

-- Reading Literature Standards
INSERT INTO public.standards (framework, region, code, text, subject, grade_band, parent_code, tags, metadata) VALUES
('CA-CCSS', 'California', 'CCSS.ELA-LITERACY.RL.9-10.1', 'Cite strong and thorough textual evidence to support analysis of what the text says explicitly as well as inferences drawn from the text.', 'English/Language Arts', '9-10', NULL, ARRAY['reading', 'literature', 'textual evidence'], '{"strand": "Reading Literature", "domain": "Key Ideas and Details"}'::jsonb),
('CA-CCSS', 'California', 'CCSS.ELA-LITERACY.RL.9-10.2', 'Determine a theme or central idea of a text and analyze in detail its development over the course of the text, including how it emerges and is shaped and refined by specific details; provide an objective summary of the text.', 'English/Language Arts', '9-10', NULL, ARRAY['reading', 'literature', 'theme'], '{"strand": "Reading Literature", "domain": "Key Ideas and Details"}'::jsonb),
('CA-CCSS', 'California', 'CCSS.ELA-LITERACY.RL.9-10.3', 'Analyze how complex characters (e.g., those with multiple or conflicting motivations) develop over the course of a text, interact with other characters, and advance the plot or develop the theme.', 'English/Language Arts', '9-10', NULL, ARRAY['reading', 'literature', 'character analysis'], '{"strand": "Reading Literature", "domain": "Key Ideas and Details"}'::jsonb),
('CA-CCSS', 'California', 'CCSS.ELA-LITERACY.RL.9-10.4', 'Determine the meaning of words and phrases as they are used in the text, including figurative and connotative meanings; analyze the cumulative impact of specific word choices on meaning and tone.', 'English/Language Arts', '9-10', NULL, ARRAY['reading', 'literature', 'vocabulary'], '{"strand": "Reading Literature", "domain": "Craft and Structure"}'::jsonb),
('CA-CCSS', 'California', 'CCSS.ELA-LITERACY.RL.9-10.5', 'Analyze how an author''s choices concerning how to structure a text, order events within it, and manipulate time create such effects as mystery, tension, or surprise.', 'English/Language Arts', '9-10', NULL, ARRAY['reading', 'literature', 'text structure'], '{"strand": "Reading Literature", "domain": "Craft and Structure"}'::jsonb),
('CA-CCSS', 'California', 'CCSS.ELA-LITERACY.RL.9-10.6', 'Analyze a particular point of view or cultural experience reflected in a work of literature from outside the United States, drawing on a wide reading of world literature.', 'English/Language Arts', '9-10', NULL, ARRAY['reading', 'literature', 'point of view'], '{"strand": "Reading Literature", "domain": "Craft and Structure"}'::jsonb),

-- Reading Informational Text Standards
('CA-CCSS', 'California', 'CCSS.ELA-LITERACY.RI.9-10.1', 'Cite strong and thorough textual evidence to support analysis of what the text says explicitly as well as inferences drawn from the text.', 'English/Language Arts', '9-10', NULL, ARRAY['reading', 'informational text', 'textual evidence'], '{"strand": "Reading Informational Text", "domain": "Key Ideas and Details"}'::jsonb),
('CA-CCSS', 'California', 'CCSS.ELA-LITERACY.RI.9-10.2', 'Determine a central idea of a text and analyze its development over the course of the text, including how it emerges and is shaped and refined by specific details; provide an objective summary of the text.', 'English/Language Arts', '9-10', NULL, ARRAY['reading', 'informational text', 'main idea'], '{"strand": "Reading Informational Text", "domain": "Key Ideas and Details"}'::jsonb),
('CA-CCSS', 'California', 'CCSS.ELA-LITERACY.RI.9-10.3', 'Analyze how the author unfolds an analysis or series of ideas or events, including the order in which the points are made, how they are introduced and developed, and the connections that are drawn between them.', 'English/Language Arts', '9-10', NULL, ARRAY['reading', 'informational text', 'analysis'], '{"strand": "Reading Informational Text", "domain": "Key Ideas and Details"}'::jsonb),
('CA-CCSS', 'California', 'CCSS.ELA-LITERACY.RI.9-10.4', 'Determine the meaning of words and phrases as they are used in a text, including figurative, connotative, and technical meanings; analyze the cumulative impact of specific word choices on meaning and tone.', 'English/Language Arts', '9-10', NULL, ARRAY['reading', 'informational text', 'vocabulary'], '{"strand": "Reading Informational Text", "domain": "Craft and Structure"}'::jsonb),
('CA-CCSS', 'California', 'CCSS.ELA-LITERACY.RI.9-10.5', 'Analyze in detail how an author''s ideas or claims are developed and refined by particular sentences, paragraphs, or larger portions of a text.', 'English/Language Arts', '9-10', NULL, ARRAY['reading', 'informational text', 'text structure'], '{"strand": "Reading Informational Text", "domain": "Craft and Structure"}'::jsonb),
('CA-CCSS', 'California', 'CCSS.ELA-LITERACY.RI.9-10.6', 'Determine an author''s point of view or purpose in a text and analyze how an author uses rhetoric to advance that point of view or purpose.', 'English/Language Arts', '9-10', NULL, ARRAY['reading', 'informational text', 'author purpose'], '{"strand": "Reading Informational Text", "domain": "Craft and Structure"}'::jsonb),

-- Writing Standards
('CA-CCSS', 'California', 'CCSS.ELA-LITERACY.W.9-10.1', 'Write arguments to support claims in an analysis of substantive topics or texts, using valid reasoning and relevant and sufficient evidence.', 'English/Language Arts', '9-10', NULL, ARRAY['writing', 'argument'], '{"strand": "Writing", "domain": "Text Types and Purposes"}'::jsonb),
('CA-CCSS', 'California', 'CCSS.ELA-LITERACY.W.9-10.2', 'Write informative/explanatory texts to examine and convey complex ideas, concepts, and information clearly and accurately through the effective selection, organization, and analysis of content.', 'English/Language Arts', '9-10', NULL, ARRAY['writing', 'informative'], '{"strand": "Writing", "domain": "Text Types and Purposes"}'::jsonb),
('CA-CCSS', 'California', 'CCSS.ELA-LITERACY.W.9-10.3', 'Write narratives to develop real or imagined experiences or events using effective technique, well-chosen details, and well-structured event sequences.', 'English/Language Arts', '9-10', NULL, ARRAY['writing', 'narrative'], '{"strand": "Writing", "domain": "Text Types and Purposes"}'::jsonb),
('CA-CCSS', 'California', 'CCSS.ELA-LITERACY.W.9-10.4', 'Produce clear and coherent writing in which the development, organization, and style are appropriate to task, purpose, and audience.', 'English/Language Arts', '9-10', NULL, ARRAY['writing', 'clarity'], '{"strand": "Writing", "domain": "Production and Distribution of Writing"}'::jsonb),
('CA-CCSS', 'California', 'CCSS.ELA-LITERACY.W.9-10.5', 'Develop and strengthen writing as needed by planning, revising, editing, rewriting, or trying a new approach, focusing on addressing what is most significant for a specific purpose and audience.', 'English/Language Arts', '9-10', NULL, ARRAY['writing', 'revision'], '{"strand": "Writing", "domain": "Production and Distribution of Writing"}'::jsonb),
('CA-CCSS', 'California', 'CCSS.ELA-LITERACY.W.9-10.6', 'Use technology, including the Internet, to produce, publish, and update individual or shared writing products, taking advantage of technology''s capacity to link to other information and to display information flexibly and dynamically.', 'English/Language Arts', '9-10', NULL, ARRAY['writing', 'technology'], '{"strand": "Writing", "domain": "Production and Distribution of Writing"}'::jsonb),

-- Speaking and Listening Standards
('CA-CCSS', 'California', 'CCSS.ELA-LITERACY.SL.9-10.1', 'Initiate and participate effectively in a range of collaborative discussions (one-on-one, in groups, and teacher-led) with diverse partners on grades 9-10 topics, texts, and issues, building on others'' ideas and expressing their own clearly and persuasively.', 'English/Language Arts', '9-10', NULL, ARRAY['speaking', 'listening', 'collaboration'], '{"strand": "Speaking and Listening", "domain": "Comprehension and Collaboration"}'::jsonb),
('CA-CCSS', 'California', 'CCSS.ELA-LITERACY.SL.9-10.2', 'Integrate multiple sources of information presented in diverse media or formats (e.g., visually, quantitatively, orally) evaluating the credibility and accuracy of each source.', 'English/Language Arts', '9-10', NULL, ARRAY['speaking', 'listening', 'media analysis'], '{"strand": "Speaking and Listening", "domain": "Comprehension and Collaboration"}'::jsonb),
('CA-CCSS', 'California', 'CCSS.ELA-LITERACY.SL.9-10.3', 'Evaluate a speaker''s point of view, reasoning, and use of evidence and rhetoric, identifying any fallacious reasoning or exaggerated or distorted evidence.', 'English/Language Arts', '9-10', NULL, ARRAY['speaking', 'listening', 'critical thinking'], '{"strand": "Speaking and Listening", "domain": "Comprehension and Collaboration"}'::jsonb),
('CA-CCSS', 'California', 'CCSS.ELA-LITERACY.SL.9-10.4', 'Present information, findings, and supporting evidence clearly, concisely, and logically such that listeners can follow the line of reasoning and the organization, development, substance, and style are appropriate to purpose, audience, and task.', 'English/Language Arts', '9-10', NULL, ARRAY['speaking', 'presentation'], '{"strand": "Speaking and Listening", "domain": "Presentation of Knowledge and Ideas"}'::jsonb),

-- Language Standards
('CA-CCSS', 'California', 'CCSS.ELA-LITERACY.L.9-10.1', 'Demonstrate command of the conventions of standard English grammar and usage when writing or speaking.', 'English/Language Arts', '9-10', NULL, ARRAY['language', 'grammar'], '{"strand": "Language", "domain": "Conventions of Standard English"}'::jsonb),
('CA-CCSS', 'California', 'CCSS.ELA-LITERACY.L.9-10.2', 'Demonstrate command of the conventions of standard English capitalization, punctuation, and spelling when writing.', 'English/Language Arts', '9-10', NULL, ARRAY['language', 'conventions'], '{"strand": "Language", "domain": "Conventions of Standard English"}'::jsonb),
('CA-CCSS', 'California', 'CCSS.ELA-LITERACY.L.9-10.3', 'Apply knowledge of language to understand how language functions in different contexts, to make effective choices for meaning or style, and to comprehend more fully when reading or listening.', 'English/Language Arts', '9-10', NULL, ARRAY['language', 'style'], '{"strand": "Language", "domain": "Knowledge of Language"}'::jsonb),
('CA-CCSS', 'California', 'CCSS.ELA-LITERACY.L.9-10.4', 'Determine or clarify the meaning of unknown and multiple-meaning words and phrases based on grades 9-10 reading and content, choosing flexibly from a range of strategies.', 'English/Language Arts', '9-10', NULL, ARRAY['language', 'vocabulary'], '{"strand": "Language", "domain": "Vocabulary Acquisition and Use"}'::jsonb),
('CA-CCSS', 'California', 'CCSS.ELA-LITERACY.L.9-10.5', 'Demonstrate understanding of figurative language, word relationships, and nuances in word meanings.', 'English/Language Arts', '9-10', NULL, ARRAY['language', 'figurative language'], '{"strand": "Language", "domain": "Vocabulary Acquisition and Use"}'::jsonb),
('CA-CCSS', 'California', 'CCSS.ELA-LITERACY.L.9-10.6', 'Acquire and use accurately general academic and domain-specific words and phrases, sufficient for reading, writing, speaking, and listening at the college and career readiness level; demonstrate independence in gathering vocabulary knowledge when considering a word or phrase important to comprehension or expression.', 'English/Language Arts', '9-10', NULL, ARRAY['language', 'academic vocabulary'], '{"strand": "Language", "domain": "Vocabulary Acquisition and Use"}'::jsonb);